// <auto-generated />
using System;
using API_Lab4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Lab4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230517141112_second try")]
    partial class secondtry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIModels.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            HobbyId = 1,
                            Description = "Love spending time in the stable, the connection with the horse, riding etc",
                            Title = "Horse-ridng"
                        },
                        new
                        {
                            HobbyId = 2,
                            Description = "The mountains, the thrill of the speed, hot chocolate, Jäger etc",
                            Title = "Skiing"
                        },
                        new
                        {
                            HobbyId = 3,
                            Description = "Enjoys going out with the boat, hoping to catch a big pike",
                            Title = "Fishing"
                        },
                        new
                        {
                            HobbyId = 4,
                            Description = "Enjoys a good match",
                            Title = "Padel"
                        },
                        new
                        {
                            HobbyId = 5,
                            Description = "The best of the Christmas, when Santa brings a puzzle",
                            Title = "Puzzle"
                        });
                });

            modelBuilder.Entity("APIModels.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<string>("WebLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            WebLink = "https://www.varbergsridskola.se"
                        },
                        new
                        {
                            LinkId = 2,
                            WebLink = "https://www.lofsdalen.com/sv/skidakning"
                        },
                        new
                        {
                            LinkId = 3,
                            WebLink = "https://www.skistar.com/sv/myskistar/destination/trysil/"
                        },
                        new
                        {
                            LinkId = 4,
                            WebLink = "https://www.visitvarberg.se/ovrigt/outdoor/outdoorsidor/fiska.html"
                        },
                        new
                        {
                            LinkId = 5,
                            WebLink = "https://minhast.se/"
                        },
                        new
                        {
                            LinkId = 6,
                            WebLink = "https://www.facebook.com/ponactive/"
                        });
                });

            modelBuilder.Entity("APIModels.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "Elin Otterdahl",
                            PhoneNumber = 706342635
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Marcus Linderholm",
                            PhoneNumber = 70834728
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Sofie Apelqvist",
                            PhoneNumber = 70726492
                        });
                });

            modelBuilder.Entity("APIModels.PersonHobbyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkId")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HobbiesPersonsLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HobbyId = 1,
                            LinkId = 1,
                            PersonID = 1
                        },
                        new
                        {
                            Id = 2,
                            HobbyId = 2,
                            LinkId = 2,
                            PersonID = 1
                        },
                        new
                        {
                            Id = 3,
                            HobbyId = 2,
                            LinkId = 3,
                            PersonID = 1
                        },
                        new
                        {
                            Id = 4,
                            HobbyId = 2,
                            LinkId = 2,
                            PersonID = 2
                        },
                        new
                        {
                            Id = 5,
                            HobbyId = 3,
                            LinkId = 4,
                            PersonID = 2
                        },
                        new
                        {
                            Id = 6,
                            HobbyId = 1,
                            LinkId = 5,
                            PersonID = 3
                        },
                        new
                        {
                            Id = 7,
                            HobbyId = 4,
                            LinkId = 6,
                            PersonID = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
